import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,Check,Leaf,Send,Sprout} from 'lucide-react';
import {Layout,Link} from './components/Layout';
import {business,solutions,partners} from './data/site';
import {contentRepository} from './services/contentRepository';
import AdminConsole from './admin/AdminConsole';
import './styles.css';

const fallback={home:{name:'메인 페이지',visible:true,title:'농업의 가능성을\n기술과 연결합니다.',description:'스마트농업 구축, 디지털 운영, 교육 콘텐츠와 지역 협력을 연결해 기술이 지속 가능한 운영과 성장으로 이어지도록 합니다.',button:'사업영역 보기',image:'',alt:'스마트농업 시설과 작물'},about:{name:'회사소개',visible:true,title:'스마트농업이 실제 현장에서 지속되도록',description:'퍼스트팜의 회사 정의와 비전, 미션을 소개합니다.',button:'회사소개 보기',image:'',alt:''},business:{name:'사업영역',visible:true,title:'기술, 운영, 교육, 협력을 연결합니다.',description:'네 가지 사업영역을 소개합니다.',button:'사업영역 보기',image:'',alt:''},solutions:{name:'솔루션',visible:true,title:'현장에 맞게 연결되는 솔루션',description:'스마트팜 구축부터 교육 콘텐츠까지 목적에 맞는 솔루션을 제공합니다.',button:'솔루션 보기',image:'',alt:''},projects:{name:'프로젝트',visible:true,title:'프로젝트',description:'실제 자료를 바탕으로 현장의 이야기를 소개합니다.',button:'프로젝트 보기',image:'',alt:''},partnership:{name:'파트너십',visible:true,title:'함께 만드는 스마트농업의 다음 연결',description:'학교, 공공기관, 기업, 농업기관과의 협력 방식을 소개합니다.',button:'협업 문의',image:'',alt:''},ir:{name:'IR',visible:true,title:'스마트농업 비즈니스 플랫폼',description:'사업 구조와 확장 방향을 소개합니다.',button:'IR 문의',image:'',alt:''},news:{name:'소식',visible:true,title:'소식',description:'프로젝트와 교육 현장, 협력 소식을 전합니다.',button:'소식 보기',image:'',alt:''},contact:{name:'문의',visible:true,title:'스마트농업의 다음 연결을 함께 만들어 보세요.',description:'도입, 협업, 제휴, 투자 문의를 기다립니다.',button:'문의 보내기',image:'',alt:''}};
const load=()=>{const saved=contentRepository.read().pages||{};return Object.fromEntries(Object.entries(fallback).map(([k,v])=>[k,{...v,...saved[k]}]));};
function Placeholder(){return <div className="placeholder"><Leaf size={25}/><span>자료 입력 필요</span><small>관리자에서 실제 콘텐츠를 추가할 수 있습니다.</small></div>}
function Hero({page,eyebrow='FIRSTFARM'}){const lines=page.title.split('\n');return <section className="page-hero" style={page.image?{backgroundImage:`linear-gradient(#143c32d9,#143c32b3),url(${page.image})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}><div><p className="eyebrow">{eyebrow}</p><h1>{lines.map((l,i)=><React.Fragment key={i}>{l}{i<lines.length-1&&<br/>}</React.Fragment>)}</h1><p>{page.description}</p></div></section>}
function Home({pages}){const h=pages.home;return <><section className="hero"><div className="hero-copy"><p className="eyebrow">AGRICULTURE · TECHNOLOGY · CONNECTION</p><h1>{h.title.split('\n').map((l,i)=><React.Fragment key={i}>{i===1?<em>{l}</em>:l}{i===0&&<br/>}</React.Fragment>)}</h1><p className="lead">{h.description}</p><div className="actions"><Link className="primary" to="/business">{h.button}<ArrowRight size={18}/></Link><Link className="text-btn" to="/solutions">솔루션 살펴보기<ArrowRight size={17}/></Link></div></div><div className="farm-art" style={h.image?{backgroundImage:`linear-gradient(#143c3299,#143c3255),url(${h.image})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}>{!h.image&&<><div className="sun"/><div className="window"><i/><i/><i/><i/></div><div className="rack"><b/><b/><b/></div><div className="plants">{Array.from({length:12}).map((_,i)=><span key={i}/>)}</div></>}<div className="tag">SMART AGRI<br/><small>{h.alt||'connected farming'}</small></div></div></section>{pages.about.visible&&<section className="intro wrap"><p className="eyebrow">ABOUT FIRSTFARM</p><div className="split"><h2>{pages.about.title}</h2><div><p>{pages.about.description}</p><Link className="under-link" to="/about">{pages.about.button}<ArrowRight size={16}/></Link></div></div></section>}{pages.business.visible&&<section className="business wrap"><p className="eyebrow">BUSINESS AREAS</p><h2>{pages.business.title}</h2><div className="cards cards-four">{business.map((x,i)=><article key={x.slug}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.summary}</p><Link className="under-link" to="/business">자세히 보기<ArrowRight size={15}/></Link></article>)}</div></section>}<section className="effects"><div className="wrap"><p className="eyebrow">CORE STRENGTHS</p><h2>연결의 구조가 <em>가능성을 만듭니다.</em></h2><div className="benefits benefits-four">{['통합 제공','운영 지속성','데이터 축적','현장 맞춤 설계'].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>실제 현장에 맞는 구성과 지속 가능한 활용 흐름을 함께 설계합니다.</p><Check/></article>)}</div></div></section></>}
function Listing({page,type}){const items=type==='business'?business:type==='solutions'?solutions:type==='partnership'?partners:[];return <><Hero page={page} eyebrow={page.name.toUpperCase()}/><section className="wrap section">{items.length?<div className="cards cards-four">{items.map((x,i)=><article key={x.slug||x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.summary||x.text||'현장에 맞는 협력과 운영 구조를 함께 설계합니다.'}</p>{x.items&&<ul>{x.items.map(a=><li key={a}>{a}</li>)}</ul>}</article>)}</div>:<Placeholder/>}</section></>}
function Contact({page}){const [sent,setSent]=useState(false);return <><Hero page={page} eyebrow="CONTACT"/><section className="wrap section contact-grid"><div><h2>도입·협업·제휴 문의</h2><p>스마트팜 구축, 교육 프로그램, 공공사업, ESG 협업, 투자와 관련한 문의를 기다립니다.</p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>기관명<input required/></label><label>담당자명<input required/></label><label>이메일<input required type="email"/></label><label>문의 내용<textarea required/></label><label className="agree"><input required type="checkbox"/> 개인정보 수집 및 이용에 동의합니다.</label><button className="primary">{page.button}<Send size={16}/></button>{sent&&<p className="sent">문의가 접수되었습니다.</p>}</form></section></>}
function App(){const [path,setPath]=useState(location.pathname);useEffect(()=>{const handle=()=>setPath(location.pathname);addEventListener('popstate',handle);return()=>removeEventListener('popstate',handle)},[]);if(path==='/admin')return <AdminConsole/>;const pages=load();const key=path==='/'?'home':path.split('/')[1]||'home';const page=pages[key]||pages.contact;if(!page.visible&&key!=='home')return <Layout><Hero page={{...page,title:'공개 준비 중',description:'이 페이지는 현재 공개 준비 중입니다.'}}/></Layout>;let view=key==='home'?<Home pages={pages}/>:key==='contact'?<Contact page={page}/>:<Listing page={page} type={key}/>;return <Layout>{view}</Layout>}
createRoot(document.getElementById('root')).render(<App/>);
